### ISSUE TITLE
Unable to add Server Name Indication

### ISSUE THREAD

**Issue by DadanielZ** [wildfly/wildfly-openssl#59]
Hi, 
I'm trying to set **Server Name Indication (SNI)** using SSLParameters, but in `"org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.jar!/org/wildfly/openssl/OpenSSLEngine.class`", "`OpenSSLEngine.setSSLParameters(SSLParameters sslParameters)`" doesn't apply "SNIServerName", it looks like a bug to me, can anyone confirm or suggest an alternative way to set SNI?  Thanks.

**Comment by vishwajeetdusane** [comment]
Wildfly native implementation does not invoke/support `SSL_set_tlsext_host_name` which would set the SNI for the request.

Fix is to add `setServerNameIndication` API in `ssl.c` which would intern call `SSL_set_tlsext_host_name` to set SNI when used for client connection. On java side, if host is available `setServerNameIndication` should be called implicitly (`OpenSSLEngine `when `clientMode` is true) before handshake is initiated otherwise as part of the `setSslParamaters` being invoked.

Without `SSL_set_tlsext_host_name` API, no way to set the SNI for the request.

@stuartwdouglas - What do you think?

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas  - Could you please review this pull request?

**Comment by vishwajeetdusane** [comment]
@stuartwdouglas When is the release planned which would include this patch?

**Comment by DadanielZ** [comment]
Thank you @vishwajeetdusane for making the fix.
This is a **blocking issue** for us.  Anyone can provide an estimated timeline for the release? @stuartwdouglas
